### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by memory009** [shikiw/SI-Adv#3]
Hello, I have completed the construction of the conda environment according to the environment.yml you gave, but when I use "python main.py --transfer_attack_method ifgm_ours" to train, the error "RuntimeError: CUDA error: no kernel image is available for execution on the device", how do I solve this problem? (Is my pytorch version too high?)

**Comment by shikiw** [comment]
Yes, I guess it is probably because your pytorch version is too high/low, which conflicts with your gpu device.

**Comment by memory009** [comment]
Thank you for your answer, as you said, my pytorch version is too low.
when I use "conda uninstall *torch* cudatoolkit" to uninstall the original pytorch, 
then "pip3 install torch==1.10.2+cu113 torchvision== 0.11.3+cu113 torchaudio==0.10.2+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html "
The problem is solved after changing to the new pytorch version
